### ISSUE TITLE
ImportError: No module named fuel.datasets 

### ISSUE THREAD

**Issue by SeekPoint** [yyaghoobzadeh/figment-multi#1]
Traceback (most recent call last):
  File "../../src/make_dataset.py", line 17, in <module>
    from fuel.datasets import H5PYDataset
ImportError: No module named fuel.datasets
building fuel datasets for sskip and fasttext...
mkdir: cannot create directory ‘sskip’: File exists
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "../../src/make_dataset.py", line 17, in <module>
    from fuel.datasets import H5PYDataset
ImportError: No module named fuel.datasets
(.venv) ub16hp@UB16HP:~/ub16_prj/figment-multi$ 
(.venv) ub16hp@UB16HP:~/ub16_prj/figment-multi$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import fuel
>>> fuel.__version__
'0.1.1'
>>> quit()
(.venv) ub16hp@UB16HP:~/ub16_prj/figment-multi$

**Comment by yyaghoobzadeh** [comment]
That shouldn't be a problem, because I have no problem with the same "fuel" version. 
Can you maybe run this:

from fuel.datasets.hdf5 import H5PYDataset 

and see if this works?

**Comment by SeekPoint** [comment]
it fiexed
